const quizData = [
{
    question: "The point at which the entire mass of a body may be considered concentrated such that internal moments about any line through the point are zero.",
    answer: "CENTER OF MASS"
  },
  {
    question: "The center of a one- or two-dimensional figure, about which the sum of the displacement of all points in the figure is zero.",
    answer: "CENTROID"
  },
  {
    question: "The physical law that a body remains at rest or in motion with a constant velocity unless an external force acts on the body.",
    answer: "NEWTON’S 1ST LAW OF MOTION"
  },
  {
    question: "The tendency of a body at rest to remain at rest or of a body in motion to continue its velocity and direction unless acted upon by an external force.",
    answer: "INERTIA"
  },
  {
    question: "Having the same translational and rotational effect on a body.",
    answer: "STATICALLY EQUIVALENT"
  },
  {
    question: "The force required to bring a set of concurrent forces into equilibrium; equal in magnitude but opposite in direction to the resultant of the concurrent force system, acting along the same line of action.",
    answer: "EQUILIBRIANT"
  },
  {
    question: "A state of balance or rest resulting from the equal action of opposing forces. For a rigid body to be in equilibrium, two conditions are necessary:",
    answer: "EQUILIBRIUM"
  },
  {
    question: "The physical law that the sum of the forces acting on a body is equal to the product of the mass of the body and the acceleration produced by the force, with motion in the direction of the resultant of the forces.",
    answer: "NEWTON’S 2ND LAW OF MOTION"
  },
  {
    question: "The physical law that for every force acting on a body, the body exerts a force having equal magnitude and the opposite direction along the same line of action as the original force. Also called the Law of Action and Reaction.",
    answer: "NEWTON’S 3RD LAW OF MOTION"
  },
  {
    question: "An external force acting directly on a body.",
    answer: "APPLIED FORCE"
  },
  {
    question: "An external force generated by the action of one body on another.",
    answer: "REACTIVE FORCE"
  },
  {
    question: "The horizontal component of resistance developed by a soil mass against the horizontal movement of a vertical structure through the soil.",
    answer: "PASSIVE EARTH PRESSURE"
  },
  {
    question: "The horizontal component of pressure that a soil mass exerts on a vertical retaining structure.",
    answer: "ACTIVE EARTH PRESSURE"
  },
  {
    question: "The actual pressure developed between a footing and the supporting soil mass, equal to the quotient of the magnitude of the forces transmitted and the area of contact. Also called contact pressure.",
    answer: "SOIL PRESSURE"
  },
  {
    question: "The maximum unit pressure a foundation is permitted to impose vertically or laterally on a supporting soil mass. Allowable bearing pressures for various soil classifications are conservative values permitted by building codes in the absence of geotechnical investigation and testing of the soil. Also called allowable bearing capacity or allowable soil pressure.",
    answer: "ALLOWABLE BEARING PRESSURE"
  },
  {
    question: "The transfer of stress from a yielding part of a soil mass to adjoining, less yielding or restrained parts of the mass.",
    answer: "ARCHING"
  },
  {
    question: "The maximum depth at which soil is frozen or frost penetrates the ground.",
    answer: "FROSTLINE"
  },
  {
    question: "An uplift in soil caused by the freezing of internal moisture.",
    answer: "FROST HEAVE"
  },
  {
    question: "A softening of soil resulting from the thawing of frozen groundwater.",
    answer: "FROST BOIL"
  },
  {
    question: "A concrete footing extended laterally to distribute the foundation load over a wide enough area that the allowable bearing capacity of the supporting soil is not exceeded.",
    answer: "SPREAD FOOTING"
  },
  {
    question: "The continuous spread footing of a foundation wall.",
    answer: "STRIP FOOTING"
  },
  {
    question: "A single spread footing supporting a freestanding column or pier.",
    answer: "ISOLATED FOOTING"
  },
  {
    question: "A reinforced concrete footing extended to support a row of columns.",
    answer: "CONTINUOUS FOOTING"
  },
  {
    question: "A reinforced concrete beam supporting a superstructure at or near ground level and transferring the load to isolated footings, piers, or piles. Also called ground beam.",
    answer: "GRADE BEAM"
  },
  {
    question: "A reinforced concrete footing connected by a tie beam to another footing in order to balance an asymmetrically imposed load, as at the perimeters of a building site. Also called strap footing.",
    answer: "CANTILEVER FOOTING"
  }
];
let quizOrder = [];
let currentAnswers = [];
let currentQuestion = 0;

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

function createQuiz() {
    // If quizOrder is not set, initialize and shuffle
    if (!quizOrder.length) {
        quizOrder = Array.from({length: quizData.length}, (_, i) => i);
        shuffleArray(quizOrder);
    }
    if (!currentAnswers.length || currentAnswers.length !== quizData.length) {
        currentAnswers = new Array(quizData.length).fill("");
    }
    const quizContainer = document.getElementById('quiz');
    quizContainer.innerHTML = '';

    quizOrder.forEach((qIdx, index) => {
        const question = quizData[qIdx];
        const questionDiv = document.createElement('div');
        questionDiv.className = 'question-container';
        if (index === 0) questionDiv.classList.add('active');

        questionDiv.innerHTML = `
            <div class="question">${index + 1}. ${question.question}</div>
            <div class="identification-input" style="display:flex;gap:8px;align-items:center;">
                <input type="text" id="input-${index}" data-q="${index}" autocomplete="off" placeholder="Type your answer..." value="${currentAnswers[index] || ''}" oninput="handleInput(${index})" />
                <button type="button" class="send-btn" id="send-${index}" onclick="sendAnswer(${index})" aria-label="Send answer" style="background:none;border:none;cursor:pointer;padding:0 6px;display:flex;align-items:center;">
                  <svg xmlns='http://www.w3.org/2000/svg' width='22' height='22' fill='none' viewBox='0 0 24 24'><path fill='var(--accent)' d='M2.01 21 23 12 2.01 3 2 10l15 2-15 2z'/></svg>
                </button>
            </div>
            <div class="feedback" id="feedback-${index}" aria-live="polite"></div>
        `;
        quizContainer.appendChild(questionDiv);
    });
    // Restore any previous answers (when resetting or revisiting)
    quizOrder.forEach((qIdx, index) => {
        if (currentAnswers[index] && currentAnswers[index] !== "") {
            const input = document.getElementById(`input-${index}`);
            if (input) input.value = currentAnswers[index];
        }
    });
    // Hide score page if visible
    const scorePage = document.getElementById('scorePage');
    if (scorePage) scorePage.style.display = 'none';
    updateNavigation();
}

// For identification: handle input and update answer
function handleInput(questionIndex) {
    const input = document.getElementById(`input-${questionIndex}`);
    currentAnswers[questionIndex] = input.value;
    // Remove feedback and enable input until send is pressed
    const feedbackEl = document.getElementById(`feedback-${questionIndex}`);
    feedbackEl.textContent = '';
    input.classList.remove('correct', 'wrong');
    updateNavigation();
}

function sendAnswer(questionIndex) {
    const input = document.getElementById(`input-${questionIndex}`);
    const feedbackEl = document.getElementById(`feedback-${questionIndex}`);
    const qIdx = quizOrder[questionIndex];
    const userAnswer = input.value.trim().toLowerCase();
    const correctAnswer = quizData[qIdx].answer.trim().toLowerCase();
    if (userAnswer !== "") {
        input.disabled = true;
        if (userAnswer === correctAnswer) {
            feedbackEl.textContent = 'Correct!';
            feedbackEl.style.color = '#2e7d32';
            input.classList.add('correct');
        } else {
            feedbackEl.textContent = `Incorrect. Correct answer: ${quizData[qIdx].answer}`;
            feedbackEl.style.color = '#c62828';
            input.classList.add('wrong');
        }
        setTimeout(() => {
            if (questionIndex < quizData.length - 1) {
                const questions = document.querySelectorAll('.question-container');
                questions[questionIndex].classList.remove('active');
                currentQuestion = questionIndex + 1;
                questions[currentQuestion].classList.add('active');
                updateNavigation();
                // Focus the next input if not already answered
                const nextInput = document.getElementById(`input-${currentQuestion}`);
                if (nextInput && !nextInput.disabled) nextInput.focus();
            }
            // Always update navigation after answer, so submit button logic is correct
            updateNavigation();
        }, 500);
    } else {
        feedbackEl.textContent = '';
        updateNavigation();
    }
}

function checkAnswers() {
    let score = 0;
    const questions = document.querySelectorAll('.question-container');

    questions.forEach((question, index) => {
        const input = question.querySelector('input[type="text"]');
        const userAnswer = (input ? input.value.trim().toLowerCase() : "");
        const qIdx = quizOrder[index];
        const correctAnswer = quizData[qIdx].answer.trim().toLowerCase();
        input.disabled = true;
        const feedbackEl = document.getElementById(`feedback-${index}`);
        if (userAnswer === correctAnswer) {
            score++;
            feedbackEl.textContent = 'Correct!';
            feedbackEl.style.color = '#2e7d32';
        } else {
            feedbackEl.textContent = `Incorrect. Correct answer: ${quizData[qIdx].answer}`;
            feedbackEl.style.color = '#c62828';
        }
    });

    // Hide all questions
    questions.forEach(q => q.style.display = 'none');

    // Show score page
    let scorePage = document.getElementById('scorePage');
    if (!scorePage) {
        scorePage = document.createElement('div');
        scorePage.id = 'scorePage';
        scorePage.className = 'score-page';
        document.getElementById('quiz').appendChild(scorePage);
    }
    scorePage.style.display = 'flex';

    const percentage = (score / quizData.length) * 100;
    scorePage.style.backgroundColor = percentage >= 70 ? '#c8e6c9' : '#ffcdd2';
    let extraMsg = '';
    if (percentage === 100) {
        extraMsg = 'iloveyoumoree baby koo galing galing talaga';
    } else if (percentage > 80) {
        extraMsg = 'kunti nalang ma perfect mo po yan baby ko';
    } else if (percentage >= 75) {
        extraMsg = 'galing naman ng baby kooo';
    } else if (percentage >= 50) {
        extraMsg = 'kaya mo yan baby';
    }
    scorePage.innerHTML = `<div style="font-weight:700;font-size:1.2rem;margin-bottom:8px;">Your score: ${score}/${quizData.length} (${percentage.toFixed(2)}%)</div>`
        + (extraMsg ? `<div class="encouragement">${extraMsg}</div>` : '')
        + `<button class="retry-btn" onclick="resetQuiz()" style="margin-top:18px;display:inline-block;">Try Again</button>`;

    // Hide navigation
    document.querySelector('.submit-btn').style.display = 'none';
    document.getElementById('nextBtn').style.display = 'none';
    document.getElementById('prevBtn').style.display = 'none';
}

function nextQuestion() {
    if (currentQuestion < quizData.length - 1) {
        const questions = document.querySelectorAll('.question-container');
        questions[currentQuestion].classList.remove('active');
        currentQuestion++;
        questions[currentQuestion].classList.add('active');
        updateNavigation();
    }
}

function previousQuestion() {
    if (currentQuestion > 0) {
        const questions = document.querySelectorAll('.question-container');
        questions[currentQuestion].classList.remove('active');
        currentQuestion--;
        questions[currentQuestion].classList.add('active');
        updateNavigation();
    }
}


function updateNavigation() {
  const prevBtn = document.getElementById('prevBtn');
  const submitBtn = document.querySelector('.submit-btn');
  const counter = document.getElementById('questionCounter');
  const progress = document.getElementById('progress');

  prevBtn.disabled = currentQuestion === 0;

  // Only show submit button on last question and only enable if last input is disabled (answer submitted)
  let showSubmit = false;
  let enableSubmit = false;
  if (currentQuestion === quizData.length - 1) {
    const lastInput = document.getElementById(`input-${currentQuestion}`);
    if (lastInput) {
      showSubmit = true;
      enableSubmit = lastInput.disabled && lastInput.value.trim() !== "";
    }
  }
  if (showSubmit) {
    submitBtn.style.display = 'block';
    submitBtn.disabled = !enableSubmit;
  } else {
    submitBtn.style.display = 'none';
  }

  counter.textContent = `Question ${currentQuestion + 1} of ${quizData.length}`;
  progress.style.width = `${((currentQuestion + 1) / quizData.length) * 100}%`;
  // Hide next button if present
  const nextBtn = document.getElementById('nextBtn');
  if (nextBtn) nextBtn.style.display = 'none';
  prevBtn.style.display = 'block';
}

function resetQuiz() {
    // Shuffle question order for new try
    quizOrder = Array.from({length: quizData.length}, (_, i) => i);
    shuffleArray(quizOrder);
    currentAnswers = new Array(quizData.length).fill("");
    currentQuestion = 0;
    const quizContainer = document.getElementById('quiz');
    quizContainer.innerHTML = '';
    createQuiz();

    // Hide score page if present
    const scorePage = document.getElementById('scorePage');
    if (scorePage) scorePage.style.display = 'none';

    document.querySelector('.submit-btn').style.display = 'none';
    // Hide all retry buttons except the one on score page
    document.querySelectorAll('.retry-btn').forEach(btn => btn.style.display = 'none');
    document.getElementById('nextBtn').style.display = 'block';
    document.getElementById('prevBtn').style.display = 'block';
    updateNavigation();
}

// Initialize the quiz when the page loads
window.onload = function() {
    quizOrder = Array.from({length: quizData.length}, (_, i) => i);
    shuffleArray(quizOrder);
    currentAnswers = new Array(quizData.length).fill("");
    createQuiz();
};
